version: '3.5'

services:
  application:
    build: ./
    restart: always
    command: ./main
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./dev/db/normalized/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    environment:
      POSTGRES_PASSWORD: TestPassword
      POSTGRES_USER: testuser
      POSTGRES_DB: test_task
    ports:
      - 5432:5432
